### ISSUE TITLE
Uso incorreto de gh-pages

### ISSUE THREAD

**Issue by LaPingvino** [RibeiroAna/ribeiroana.github.io#1]
Usa-se o branch gh-pages se quiser fazer uma página num repositório aleatório, ou o branch master se faz uma página na estrutura algo.github.io, então para que a página funcione tem que mudar de branch, [como tem escrito no Help](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages).

**Comment by RibeiroAna** [comment]
Obrigada Joop, fiz isso sem prestar atenção, já tinha feito outra página pessoal com anaribeiro, mas a tinha excluído. ^^
